#!/bin/bash

gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Criar tela de cadastro com envio de documentos obrigatórios" --body "Criar funcionalidade: [Motorista] Criar tela de cadastro com envio de documentos obrigatórios"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Backend - Upload e validação de documentos" --body "Criar funcionalidade: [Motorista] Backend - Upload e validação de documentos"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Exibir mensagem de “Cadastro em análise” após envio" --body "Criar funcionalidade: [Motorista] Exibir mensagem de “Cadastro em análise” após envio"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Criar tela de login" --body "Criar funcionalidade: [Motorista] Criar tela de login"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Criar tela de dashboard com listagem de veículos disponíveis" --body "Criar funcionalidade: [Motorista] Criar tela de dashboard com listagem de veículos disponíveis"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Criar tela de solicitação de aluguel" --body "Criar funcionalidade: [Motorista] Criar tela de solicitação de aluguel"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Backend - Enviar solicitação de aluguel ao admin" --body "Criar funcionalidade: [Motorista] Backend - Enviar solicitação de aluguel ao admin"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Tela para acompanhamento de status de solicitações" --body "Criar funcionalidade: [Motorista] Tela para acompanhamento de status de solicitações"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Exibir contrato digital após aprovação de aluguel" --body "Criar funcionalidade: [Motorista] Exibir contrato digital após aprovação de aluguel"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Assinatura digital do contrato pelo motorista" --body "Criar funcionalidade: [Motorista] Assinatura digital do contrato pelo motorista"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Exibir status “em uso” após pagamento confirmado" --body "Criar funcionalidade: [Motorista] Exibir status “em uso” após pagamento confirmado"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Criar tela de aluguéis ativos e históricos" --body "Criar funcionalidade: [Motorista] Criar tela de aluguéis ativos e históricos"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Liberar avaliação após devolução do veículo" --body "Criar funcionalidade: [Motorista] Liberar avaliação após devolução do veículo"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Motorista] Tela de avaliação de aluguel" --body "Criar funcionalidade: [Motorista] Tela de avaliação de aluguel"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Tela de login exclusiva para administrador" --body "Criar funcionalidade: [Admin] Tela de login exclusiva para administrador"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Listar motoristas pendentes para aprovação" --body "Criar funcionalidade: [Admin] Listar motoristas pendentes para aprovação"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Visualizar documentos enviados pelos motoristas" --body "Criar funcionalidade: [Admin] Visualizar documentos enviados pelos motoristas"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Aprovar ou recusar cadastro de motorista" --body "Criar funcionalidade: [Admin] Aprovar ou recusar cadastro de motorista"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Bloquear/desbloquear motorista ativo" --body "Criar funcionalidade: [Admin] Bloquear/desbloquear motorista ativo"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Tela de cadastro de novo veículo" --body "Criar funcionalidade: [Admin] Tela de cadastro de novo veículo"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Upload de fotos dos veículos" --body "Criar funcionalidade: [Admin] Upload de fotos dos veículos"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Alterar status do veículo (disponível, em uso, manutenção)" --body "Criar funcionalidade: [Admin] Alterar status do veículo (disponível, em uso, manutenção)"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Editar dados de veículos existentes" --body "Criar funcionalidade: [Admin] Editar dados de veículos existentes"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Listar solicitações de aluguel pendentes" --body "Criar funcionalidade: [Admin] Listar solicitações de aluguel pendentes"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Visualizar detalhes da solicitação e do motorista" --body "Criar funcionalidade: [Admin] Visualizar detalhes da solicitação e do motorista"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Aprovar ou recusar solicitação" --body "Criar funcionalidade: [Admin] Aprovar ou recusar solicitação"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Gerar contrato digital de aluguel" --body "Criar funcionalidade: [Admin] Gerar contrato digital de aluguel"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Marcar pagamento como confirmado (presencial)" --body "Criar funcionalidade: [Admin] Marcar pagamento como confirmado (presencial)"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Atualizar status para “em uso”" --body "Criar funcionalidade: [Admin] Atualizar status para “em uso”"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Confirmar devolução do veículo" --body "Criar funcionalidade: [Admin] Confirmar devolução do veículo"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Liberar avaliação para o motorista" --body "Criar funcionalidade: [Admin] Liberar avaliação para o motorista"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Visualizar avaliações recebidas" --body "Criar funcionalidade: [Admin] Visualizar avaliações recebidas"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Relatório de motoristas aprovados, pendentes e bloqueados" --body "Criar funcionalidade: [Admin] Relatório de motoristas aprovados, pendentes e bloqueados"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Relatório de veículos disponíveis, em uso e em manutenção" --body "Criar funcionalidade: [Admin] Relatório de veículos disponíveis, em uso e em manutenção"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Relatório de aluguéis ativos, encerrados e recusados" --body "Criar funcionalidade: [Admin] Relatório de aluguéis ativos, encerrados e recusados"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Relatório de avaliações médias dos motoristas" --body "Criar funcionalidade: [Admin] Relatório de avaliações médias dos motoristas"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Admin] Relatório financeiro (alugueis por período)" --body "Criar funcionalidade: [Admin] Relatório financeiro (alugueis por período)"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Backend] Integração com sistema de assinatura digital (gov.br ou alternativa)" --body "Criar funcionalidade: [Backend] Integração com sistema de assinatura digital (gov.br ou alternativa)"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Backend] Criptografar senhas com bcrypt" --body "Criar funcionalidade: [Backend] Criptografar senhas com bcrypt"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Backend] Autenticação via JWT" --body "Criar funcionalidade: [Backend] Autenticação via JWT"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Backend] Middleware de proteção de rotas privadas" --body "Criar funcionalidade: [Backend] Middleware de proteção de rotas privadas"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Backend] Validação de uploads (tipos e tamanhos permitidos)" --body "Criar funcionalidade: [Backend] Validação de uploads (tipos e tamanhos permitidos)"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Ajuste] Remover rota de criação de motorista pelo admin" --body "Criar funcionalidade: [Ajuste] Remover rota de criação de motorista pelo admin"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Ajuste] Remover botão/link de cadastro de motorista no painel admin" --body "Criar funcionalidade: [Ajuste] Remover botão/link de cadastro de motorista no painel admin"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Ajuste] Manter apenas aprovação e visualização de motoristas pelo admin" --body "Criar funcionalidade: [Ajuste] Manter apenas aprovação e visualização de motoristas pelo admin"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Ajuste] Redirecionar login do motorista para sua dashboard específica" --body "Criar funcionalidade: [Ajuste] Redirecionar login do motorista para sua dashboard específica"
gh issue create --repo MARCELOASSIS87/LocPocos --title "[Ajuste] Criar sidebar personalizada para o papel 'motorista'" --body "Criar funcionalidade: [Ajuste] Criar sidebar personalizada para o papel 'motorista'"
